#
# A GitLab CI file to build a docker image on push when the commit is tagged
# NOTE - Tags aren't pushed by default, you can `git push --tags` each time
#        or `git config --global push.followTags true`
#

run-automated-tests:
  image: node:12-alpine
  only:
    - branches
    - merge_requests
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules
  script:
    - npm install --no-audit --no-optional &> /dev/null
    - npm run test -- --runInBand

#
# ref: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
#
build-versioned-docker-image:
  only:
    - tags
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
